package dev.syoritohatsuki.nebuladesktop.ui

import androidx.compose.ui.graphics.Color

val BACKGROUND_COLOR = Color(0xFF1E1E1E)

val CARD_BACKGROUND_COLOR = Color(0xFF2D2D2D)
val CARD_SELECTED_BACKGROUND_COLOR = Color(0xFF3C3C3C)

val SIDEBAR_BACKGROUND_COLOR = Color(0xFF252526)

val LOGS_BACKGROUND_COLOR = Color(0xFF111111)
val LOGS_BORDER_COLOR = Color(0xFF3C3C3C)

val TEXT_COLOR = Color(0xFFFFFFFF)
val TEXT_COLOR_SECONDARY = Color(0xFFCCCCCC)

val START_BUTTON_COLOR = Color(0xFF2ECC71)
val STOP_BUTTON_COLOR = Color(0xFFE74C3C)
val AWAIT_BUTTON_COLOR = Color(0xFFE67E22)
val ADD_BUTTON_COLOR = Color(0xFF3498DB)

val ENABLED_ICON_COLOR = Color(0xFF2ECC71)
val DISABLED_ICON_COLOR = Color(0xFFE74C3C)
val AWAIT_ICON_COLOR = Color(0xFFE67E22)