package dev.syoritohatsuki.nebuladesktop.ui

import androidx.compose.ui.graphics.Color

/*   Colors Palette   */
val TURQUOISE = Color(0xFF1ABC9C)
val EMERALD = Color(0xFF2ECC71)
val PETER_RIVER = Color(0xFF3498DB)
val AMETHYST = Color(0xFF9B59B6)
val WET_ASPHALT = Color(0xFF34495E)
val GREEN_SEA = Color(0xFF16A085)
val NEPHRITIS = Color(0xFF27AE60)
val BELIZE_HOLE = Color(0xFF2980B9)
val WISTERIA = Color(0xFF8E44AD)
val MIDNIGHT_BLUE = Color(0xFF2C3E50)
val SUN_FLOWER = Color(0xFFF1C40F)
val CARROT = Color(0xFFE67E22)
val ALIZARIN = Color(0xFFE74C3C)
val CLOUDS = Color(0xFFECF0F1)
val CONCRETE = Color(0xFF95A5A6)
val ORANGE = Color(0xFFF39C12)
val PUMPKIN = Color(0xFFD35400)
val POMEGRANATE = Color(0xFFC0392B)
val SILVER = Color(0xFFBDC3C7)
val ASBESTOS = Color(0xFF7F8C8D)

/*   Material Neutrals Palette (Gray)   */
val NEUTRAL_0 = Color(0xFF000000)
val NEUTRAL_4 = Color(0xFF0F0F0F)
val NEUTRAL_6 = Color(0xFF121212)
val NEUTRAL_10 = Color(0xFF1E1E1E)
val NEUTRAL_12 = Color(0xFF222222)
val NEUTRAL_17 = Color(0xFF2D2D2D)
val NEUTRAL_22 = Color(0xFF383838)
val NEUTRAL_30 = Color(0xFF4A4A4A)
val NEUTRAL_80 = Color(0xFFCCCCCC)
val NEUTRAL_90 = Color(0xFFE6E6E6)
val NEUTRAL_95 = Color(0xFFF2F2F2)
val NEUTRAL_100 = Color(0xFFFFFFFF)

val BACKGROUND_COLOR = NEUTRAL_10

val CARD_BACKGROUND_COLOR = NEUTRAL_17
val CARD_SELECTED_BACKGROUND_COLOR = NEUTRAL_22

val SIDEBAR_BACKGROUND_COLOR = NEUTRAL_12

val LOGS_BACKGROUND_COLOR = NEUTRAL_6
val LOGS_BORDER_COLOR = NEUTRAL_22

val TEXT_COLOR = NEUTRAL_100
val TEXT_COLOR_SECONDARY = NEUTRAL_80

val START_BUTTON_COLOR = EMERALD
val STOP_BUTTON_COLOR = ALIZARIN
val AWAIT_BUTTON_COLOR = CARROT
val ADD_BUTTON_COLOR = PETER_RIVER

val ENABLED_ICON_COLOR = EMERALD
val DISABLED_ICON_COLOR = ALIZARIN
val AWAIT_ICON_COLOR = CARROT

val PROGRESS_BAR_COLOR = PETER_RIVER
val PROGRESS_BAR_BACKGROUND_COLOR = BELIZE_HOLE