name: Linux Release

on:
  push:

  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Linux native distributions
        run: ./gradlew :composeApp:packageReleaseDistributionForCurrentOS

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            composeApp/build/compose/binaries/main-release/deb/*.deb
            composeApp/build/compose/binaries/main-release/rpm/*.rpm
