name: Linux Release

on:
  push:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          
      - name: Get latest version from build.gradle.kts
        id: version
        run: |
          VERSION=$(grep -oE 'val version\s*=\s*".*"' composeApp/build.gradle.kts | tail -n1 | sed -E 's/val version\s*=\s*"([^"]+)"/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: "Debug: print extracted version"
        run: echo "Gradle version = ${{ steps.version.outputs.version }}"

      - name: Build Linux native distributions
        run: ./gradlew :composeApp:packageReleaseDistributionForCurrentOS

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Nebula Desktop ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          files: |
            composeApp/build/compose/binaries/main-release/deb/*.deb
            composeApp/build/compose/binaries/main-release/rpm/*.rpm        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
